### ISSUE TITLE
Mythril hangs when firing the lasers at this contract.

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/mythril#341] opened 2018-07-14 19:36 UTC
```
$ myth -x MemoryArrayBuilding.sol
     
```

**MemoryArrayBuilding.sol file contents:** 
```
     1	// This code has not been professionally audited, therefore I cannot make any promises about
     2	// safety or correctness. Use at own risk.

     3	pragma solidity ^0.4.20;

     4	contract MemoryArrayBuilding {

     5	    struct Item {
     6	        string name;
     7	        string category;
     8	        address owner;
     9	        uint32 zipcode;
    10	        uint32 price;
    11	    }

    12	    Item[] public items;

    13	    mapping(address => uint) public ownerItemCount;

    14	    function getItemIDsByOwner(address _owner) public view returns (uint[]) {
    15	        uint[] memory result = new uint[](ownerItemCount[_owner]);
    16	        uint counter = 0;

    17	        for (uint i = 0; i < items.length; i++) {
    18	            if (items[i].owner == _owner) {
    19	                result[counter] = i;
    20	                counter++;
    21	            }
    22	        }
    23	        return result;
    24	    }
    25	}

```

To reproduce this bug [copy the contract](https://raw.githubusercontent.com/chronaeon/solidity-patterns/master/MemoryArrayBuilding/MemoryArrayBuilding.sol) to your pc and `myth -x` it like it's hawt.

**Comment by norhh** [comment] 2018-07-14 20:08
currently i am not sure why it's taking lot of time, can you try running it with a --max-depth of 17(or anything less than that) in that case it seems to be giving results in a reasonable amount of time.

**Comment by JoranHonig** [comment] 2018-07-20 13:59
It seems like this piece of code results in a lot of time spent in the integer module. This might improve a bit with the callback refactor #226

**Comment by JoranHonig** [comment] 2018-08-03 11:46
I'll close this issue as a duplicate of #226 if thats okay with you @chronaeon

**Closed by JoranHonig** 2018-08-03 11:46 UTC
Labels: Performance, laser, to do
