### ISSUE TITLE
Running into JSONDecodeError

### ISSUE THREAD

**Issue by joequant** [ConsenSys/mythril#1468] opened 2021-03-19 06:47 UTC
## Description

...
[joe@acer nutmeg (dev/joes-stuff)]$ ~/.local/bin/myth analyze  contracts/mock/MockCERC20.sol 
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 843, in parse_args_and_execute
    address = load_code(disassembler, args)
  File "/home/joe/.local/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 633, in load_code
    address, _ = disassembler.load_from_solidity(
  File "/home/joe/.local/lib/python3.8/site-packages/mythril/mythril/mythril_disassembler.py", line 175, in load_from_solidity
    self.sigs.import_solidity_file(
  File "/home/joe/.local/lib/python3.8/site-packages/mythril/support/signatures.py", line 245, in import_solidity_file
    solc_json = get_solc_json(file_path, solc_binary, solc_settings_json)
  File "/home/joe/.local/lib/python3.8/site-packages/mythril/ethereum/util.py", line 79, in get_solc_json
    result = json.loads(out)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by joequant** [comment] 2021-03-19 06:49
[MockWETH.sol.txt](https://github.com/ConsenSys/mythril/files/6169135/MockWETH.sol.txt)

**Comment by joequant** [comment] 2021-03-19 06:53
But its happening in every contract.  I think that the solidity compiler is not getting
run.

**Comment by norhh** [comment] 2021-03-22 12:53
@joequant does this happen when run on mythril docker image, as I can't seem to reproduce it.

**Comment by norhh** [comment] 2021-04-04 11:44
@joequant is it possible for you to paste the output `pip freeze` here, since it seems to be version dependent.

**Comment by littlezigy** [comment] 2021-08-02 10:45
> @joequant does this happen when run on mythril docker image, as I can't seem to reproduce it.

Hi. i get this error message in the docker image when I try to use the --solc-json argument.

**Comment by norhh** [comment] 2021-08-04 18:17
This should be fixed now

**Closed by norhh** 2021-08-04 18:17 UTC
Labels: Type: bug 🐛
