### ISSUE TITLE
IndexError: pop from empty list on max-depth

### ISSUE THREAD

**Issue by dmuhs** [ConsenSys/mythril#111] opened 2018-04-10 13:45 UTC
Running the following command `myth -xia 0xcafe1a77e84698c83ca8931f54a755176ef75f2c -o json` results in large RAM consumption during analysis (roughly 8GB on my machine). To limit resource usage, I added `--max-depth 8`. This resulted in the following unexpected stack trace:
```
myth -xia 0xcafe1a77e84698c83ca8931f54a755176ef75f2c -o json --max-depth 8
Traceback (most recent call last):
  File "mythril/myth", line 379, in <module>
    sym = SymExecWrapper(contract, address, max_depth=args.max_depth)
  File "/home/spoons/eth-analysis/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 263, in sym_exec
    node = self._sym_exec(gblState)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  [Previous line repeated 8 more times]
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 891, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 840, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 891, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 891, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 840, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 840, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 915, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 840, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 891, in _sym_exec
    new_node = self._sym_exec(new_gblState, depth=depth + 1, constraints=new_constraints)
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 399, in _sym_exec
    state.stack.append((helper.pop_bitvec(state) + helper.pop_bitvec(state)))
  File "/home/spoons/.local/lib/python3.6/site-packages/laser/ethereum/helper.py", line 49, in pop_bitvec
    item = state.stack.pop()
IndexError: pop from empty list
```
`--max-depth 7` works just fine, every depth greater 7 results in an error.
The source code of the contract might also be of help and luckily is available at https://etherscan.io/address/0xcafe1a77e84698c83ca8931f54a755176ef75f2c#code

**Comment by jo-tud** [comment] 2018-04-11 20:09
I can confirm this problem, reproduced it on my machine.

**Comment by b-mueller** [comment] 2018-05-08 05:10
@JoranHonig, can you take this one on?

**Comment by JoranHonig** [comment] 2018-05-08 12:08
yeah

**Comment by JoranHonig** [comment] 2018-05-09 21:16
It seems that the first problem was caused by a bug in laser where mload would not always be executed correctly (if it had an symbolic index). Fixed with https://github.com/b-mueller/laser-ethereum/pull/19

The second problem is caused by another bug in laser that is still in there, ln 916 of svm.py does not always increase the depth on a jumpi. Fixed in open pr: https://github.com/b-mueller/laser-ethereum/pull/20

I can happily report that the following took about 10 seconds (after the fix):
```
/home/walker/dev/mythril/venv/bin/python /home/walker/dev/mythril/myth -xia 0xcafe1a77e84698c83ca8931f54a755176ef75f2c -o json
{"success": true, "error": null, "issues": []}
```

**Comment by b-mueller** [comment] 2018-05-30 06:38
Closing this as a duplicate of #177.

**Closed by b-mueller** 2018-05-30 06:38 UTC
Labels: Performance, bug, duplicate, to do
