### ISSUE TITLE
ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by roynalnaruto** [ConsenSys/mythril#497] opened 2018-09-06 07:04 UTC
## Description

Error while running mythril on truffle project through the docker container. A few contracts are analysed correctly, and then I see the following issue:
```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.18.11', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/interfaces/cli.py", line 147, in main
    mythril.analyze_truffle_project(args)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/mythril.py", line 183, in analyze_truffle_project
    return analyze_truffle_project(self.sigs, *args, **kwargs)  # just passthru by passing signatures for now
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/support/truffle.py", line 51, in analyze_truffle_project
    sym = SymExecWrapper(ethcontract, address, args.strategy, max_depth=args.max_depth)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/analysis/symbolic.py", line 30, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 61, in sym_exec
    transaction.run(self.open_states, self)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/transaction.py", line 58, in run
    evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 71, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 97, in execute_state
    new_global_states = Instruction(op_code, self.dynamic_loader).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 69, in evaluate
    return instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 34, in wrapper
    new_global_states = func(self, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 552, in codecopy_
    int(bytecode[2*(concrete_code_offset + i): 2*(concrete_code_offset + i + 1)], 16)
ValueError: invalid literal for int() with base 16: ''
```

## How to Reproduce

The repository I am trying to run this on, is a public repository: https://github.com/DigixGlobal/dao-contracts

```
$ docker run -v $(pwd):/tmp -w "/tmp/" mythril/myth --truffle
```

## Environment

* OS
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

* Docker version:
```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

* Python version:
```
$ python --version
Python 3.5.6
$ python3 --version
Python 3.5.6
```

* Mythril version:
```
$ docker run mythril/myth --version
Mythril version v0.18.11
```

* Solidity compiler and version: `solc --version`
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```

**Comment by norhh** [comment] 2018-09-06 07:54
hi @roynalnaruto , thanks for pointing it out, this issue was fixed in master but we are yet to have a release(hopefully in a few days), till then can you use the master branch? as it is quite stable.

**Comment by roynalnaruto** [comment] 2018-09-06 08:26
Hi @norhh, thanks for the quick response.
so I can create the docker image from the `master` branch?
I am trying to run the `docker_build_and_deploy.sh` script, this is the output:
```
./docker_build_and_deploy.sh: 2: set: Illegal option -o pipefail
```

How can build the Dockerfile (what options) to run a container from master branch?

**Comment by birdofpreyru** [comment] 2018-09-06 13:38
@roynalnaruto do you mount folder with contracts to the Docker container, as mentioned [here](https://github.com/ConsenSys/mythril/wiki/With-Docker)?

**Comment by roynalnaruto** [comment] 2018-09-07 02:47
@norhh I also tried to install the python package by `python setup.py install`

My python version is `3.5.6`

On running `myth --version` I see this error:
```
Traceback (most recent call last):
  File "/home/rohit/.local/bin/myth", line 6, in <module>
    import mythril.interfaces.cli
  File "/home/rohit/.local/lib/python3.5/site-packages/mythril/interfaces/cli.py", line 16, in <module>
    from mythril.mythril import Mythril
  File "/home/rohit/.local/lib/python3.5/site-packages/mythril/mythril.py", line 13, in <module>
    from ethereum import utils
  File "/home/rohit/.local/lib/python3.5/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/home/rohit/.local/lib/python3.5/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/home/rohit/.local/lib/python3.5/site-packages/ethereum/utils.py", line 11, in <module>
    import rlp
  File "/home/rohit/.local/lib/python3.5/site-packages/rlp/__init__.py", line 1, in <module>
    from . import sedes  # noqa: F401
  File "/home/rohit/.local/lib/python3.5/site-packages/rlp/sedes/__init__.py", line 4, in <module>
    from .big_endian_int import BigEndianInt, big_endian_int  # noqa: F401
  File "/home/rohit/.local/lib/python3.5/site-packages/rlp/sedes/big_endian_int.py", line 1, in <module>
    from eth_utils import (
  File "/home/rohit/.local/lib/python3.5/site-packages/eth_utils/__init__.py", line 24, in <module>
    from .applicators import (  # noqa: F401
  File "/home/rohit/.local/lib/python3.5/site-packages/eth_utils/applicators.py", line 43, in <module>
    def combine_argument_formatters(*formatters: List[Callable[..., Any]]) -> Formatters:
  File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)
  File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)
  File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)
  File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)
  File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
    for t in types:
TypeError: 'ellipsis' object is not iterable
```

This error was I think fixed after Python 3.5.2, so it should not occur for me. Is there some dependency issues? Have you guys faced an issue like this?

I think building and using the Docker image would be far more comfortable, but that too has an issue for me (the comment above)

**Comment by roynalnaruto** [comment] 2018-09-07 06:17
@norhh `python3.5 --version` also shows `3.5.6`

**Comment by birdofpreyru** [comment] 2018-09-07 08:30
@roynalnaruto it is weird that Docker does not work for you.

Can you try to compile your project to bytecode and then run analysis on the bytecode, like
`$ docker run mythril/myth -xc aabc`
If this will work, then I'd say the problem is with your Docker setup and permissions to access your host filesystem. Otherwise, something wrong with Docker build or the latest Mythril version itself.

**Comment by norhh** [comment] 2018-09-07 12:11
@birdofpreyru it wasn't exactly the docker problem, there was a bug with the previous version and so when he tried to build docker on master branch he is having some issues to build.

**Comment by norhh** [comment] 2018-09-22 14:53
hey @roynalnaruto , can you use the latest version of mythril 0.18.12, it doesn't have this bug

**Closed by norhh** 2018-09-22 14:53 UTC
Labels: bug, in progress

**Comment by roynalnaruto** [comment] 2018-09-24 08:52
@norhh you mean, try to build docker image from the 0.18.12 release available?

**Comment by roynalnaruto** [comment] 2018-09-24 09:12
> hey @roynalnaruto , can you use the latest version of mythril 0.18.12, it doesn't have this bug

@norhh can you please provide me with the necessary steps to proceed in doing so? I downloaded the 0.18.12 tar.gz file from the releases page. I am on an ubuntu 16.04 machine.

**Comment by norhh** [comment] 2018-09-24 09:31
@roynalnaruto , can you try doing `pip install mythril==0.18.12` .It might be good to do it in python's virtual environment.

**Comment by roynalnaruto** [comment] 2018-09-24 10:03
@norhh I am in python's virtualenv, and I installed mythril==0.18.12.

When I run `myth --version` in the virtualenv, I see this:
```
AttributeError: /home/rohit/Downloads/z3-4.7.1-x64-ubuntu-16.04/bin/libz3.so: undefined symbol: Z3_mk_lambda
```

Any other command to setup and install the z3 libraries?

**Comment by roynalnaruto** [comment] 2018-09-25 01:11
@norhh Ok, I think from a virtual environment it can work. I am trying to analyse a truffle project, which has a directory structure, with the contract `.sol` files inside those directories. It also imports contracts from `node_modules` directory. Mythril output says the file is outside of allowed directories. How do I explicitly set all of those directories as allowed?
```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.18.12', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.5/site-packages/mythril-0.18.12-py3.5.egg/mythril/interfaces/cli.py", line 154, in main
    mythril.analyze_truffle_project(args)
  File "/usr/local/lib/python3.5/site-packages/mythril-0.18.12-py3.5.egg/mythril/mythril.py", line 180, in analyze_truffle_project
    return analyze_truffle_project(self.sigs, *args, **kwargs)  # just passthru by passing signatures for now
  File "/usr/local/lib/python3.5/site-packages/mythril-0.18.12-py3.5.egg/mythril/support/truffle.py", line 43, in analyze_truffle_project
    sigs.import_from_solidity_source(contractdata['sourcePath'])
  File "/usr/local/lib/python3.5/site-packages/mythril-0.18.12-py3.5.egg/mythril/support/signatures.py", line 181, in import_from_solidity_source
    self.signatures.update(SignatureDb.get_sigs_from_file(file_path))
  File "/usr/local/lib/python3.5/site-packages/mythril-0.18.12-py3.5.egg/mythril/support/signatures.py", line 217, in get_sigs_from_file
    raise CompilerError("Solc experienced a fatal error (code %d).\n\n%s" % (ret, stderr.decode('UTF-8')))
mythril.exceptions.CompilerError: Solc experienced a fatal error (code 1).

/home/rohit/Develop/dao-contracts/contracts/storage/DaoUpgradeStorage.sol:3:1: Error: Source "@digix/cacp-contracts-dao/contracts/ResolverClient.sol" not found: File outside of allowed directories.
import "@digix/cacp-contracts-dao/contracts/ResolverClient.sol";
^--------------------------------------------------------------^
/home/rohit/Develop/dao-contracts/contracts/storage/DaoUpgradeStorage.sol:4:1: Error: Source "/home/rohit/Develop/dao-contracts/contracts/common/DaoConstants.sol" not found: File outside of allowed directories.
import "../common/DaoConstants.sol";
^----------------------------------^
```

**Comment by roynalnaruto** [comment] 2018-09-25 02:17
@norhh so I have tried using `--allow-paths .` to compile the `contracts/storage/DaoUpgradeStorage.sol` contract using this:
```
solc --allow-paths . --bin -o compiledout contracts/storage/DaoUpgradeStorage.sol
```
and it compiles successfully.

But when I use `--solc-args "--allow-paths ."` along with the mythril command, it still doesn't work and throws the same issue that the file is not in allowed directories.
```
myth --solc-args "--allow-paths ." --truffle
```

How am I supposed to use the `solc-args` option?

**Comment by norhh** [comment] 2018-09-25 09:58
@roynalnaruto , currently `--truffle` option uses truffle's build source, so currently it doesn't have a support for the `--solc-args` option

**Comment by roynalnaruto** [comment] 2018-09-26 01:38
@norhh So how do I allow those paths from `node_modules`? Also, this means Mythril will not be able to analyse a truffle project with contracts inside a directory structure as the `dao-contracts` repository?

**Comment by norhh** [comment] 2018-09-26 11:39
i think just the `--truffle` option might do that, I am not totally sure, But the truffle module is currently outdated and we are planning to remove that as we are integrating mythril platform with truffle in the near future.

**Comment by roynalnaruto** [comment] 2018-09-27 02:02
@norhh the `--truffle` option throws the error that some paths are not allowed (this error is thrown by `solc`). As I have mentioned in [this](https://github.com/ConsenSys/mythril/issues/497#issuecomment-424174460) comment.

**Comment by maxsam4** [comment] 2018-10-11 04:53
I am on version 0.18.12 and I am facing this issue as well with `--truffle`.

**Comment by norhh** [comment] 2018-10-11 06:35
Yeah the ‘—truffle’ option is broken

**Comment by ecouffes** [comment] 2018-10-22 16:30
On version 0.18.11, "--truffle" option works well with both Docker and Mythril installed with pip on Mac.

**Comment by roynalnaruto** [comment] 2018-10-23 05:46
@ecouffes 
> On version 0.18.11, "--truffle" option works well with both Docker and Mythril installed by pip on Mac.

Yea, it works on my Mac too, but not on Ubuntu.
@norhh any updates on this issue?
