### ISSUE TITLE
Contract db

### ISSUE THREAD

**Issue by Xeenych** [ConsenSys/mythril#44] opened 2018-01-11 14:27 UTC
There are two types of contracts in blockchain.
1. Contracts created by normal addresses
2. Contracts created by other contracts

The first are easy to get from node. Just get every transaction in every block and check if it creates a contract. This takes aproximatellly a day and a half

The second is complicated
You can take every transaction in every block. Check its destination address and check it code. If code is not empty, then this is contract. So you will get all contracts, created by other contracts.
But you will not get any contract, that is interacted with by other contracts only.

The complete solution is to trace every transaction in blockchain and see if it results in contract creation.

Another solution is to directly read LevelDb. Don't know if it is possible.

What way does Mythril use to build contract db?

**Comment by b-mueller** [comment] 2018-01-12 00:53
Hi @Xeenych, currently Mythril only does 1. -  look for contract creation transactions. The complete solution would probably be very slow, but perhaps we could add a command line option?

> Another solution is to directly read LevelDb. Don't know if it is possible.

This [has been on the wishlist](https://github.com/ConsenSys/mythril/issues/15) for a long time. It's possible but difficult to implement.

**Comment by b-mueller** [comment] 2018-01-20 07:21
Closing this as a duplicate of #15

**Closed by b-mueller** 2018-01-20 07:21 UTC
