### ISSUE TITLE
The incredibly poorly written javascript on your website does not inspire confidence

### ISSUE THREAD

**Issue by wade-welles** [ConsenSys/mythril#1207] opened 2019-09-04 15:22 UTC
You have a site that is basically a business card, but it freezes the entire browser because you clearly have some fundamental lack of understanding how javascript works. 

Doing this and then claiming some sort of security expert, providing a service to provide more security to smart contracts seems a bit reckless.

**Comment by b-mueller** [comment] 2019-09-04 16:52
Hey @wade-welles, I feel your pain! I assume you're taking about https://mythx.io? You would have _loved_ the original version which was written in Adobe Flash.

Seriously though, sorry for the bad experience. We're still in beta and lots of updates to the website are coming. I haven't heard reports of browser freezes so far, can you provide mode detailed information on what happened? Browser version, URL visited & any web console errors would be helpful.

**Comment by step21** [comment] 2019-09-04 21:16
Well, smart contract security and website performance are not necessarily related and maybe not done by the same people either ;)
Just, FYI, on Firefox, Linux and macOS everything is fine. Obviously some of the graphics use some ressources, but based on a quick profiler run nothing serious. Certainly nothing that should freeze your browser.

**Comment by nbanmp** [comment] 2019-09-16 14:32
Closing this issue, as it is not related to mythril itself and we are unable to reproduce the issue.

**Closed by nbanmp** 2019-09-16 14:32 UTC
