### ISSUE TITLE
Crash with TypeError

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#286] opened 2018-06-19 07:36 UTC
**Describe the bug**

Mythril crashes on LinniaRecords.sol (https://github.com/ConsenSys/Linnia-Smart-Contracts/blob/master/contracts/LinniaRecords.sol):

```Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.18.5', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/mythril.py", line 323, in fire_lasers
    max_depth=max_depth)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 265, in sym_exec
    node = self._sym_exec(gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 911, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 911, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 911, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 897, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 897, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 852, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 897, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 911, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 852, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 897, in _sym_exec
    new_node = self._sym_exec(new_gblState)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/svm.py", line 1005, in _sym_exec
    data = natives.native_contracts(int(callee_address, 16 ), calldata)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/natives.py", line 78, in native_contracts
    return functions[address-1](data)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.5-py3.6.egg/mythril/laser/ethereum/natives.py", line 43, in ecrecover
    data = bytearray(data)
TypeError: an integer is required```

**Comment by norhh** [comment] 2018-06-19 09:39
got the reason for the error, how can i assign this to myself?
Will mostly fix this by tonight and change the tests(as this case was missed in it).

**Comment by norhh** [comment] 2018-06-19 15:50
[0001-add-typecheck-for-the-contracts.txt](https://github.com/ConsenSys/mythril/files/2115929/0001-add-typecheck-for-the-contracts.txt)

This is the patch should mostly fix the bug

**Comment by birdofpreyru** [comment] 2018-06-19 16:16
@norhh if you sure it fixes the problem, feel free to merge: merging / testing of patches is a part of duties :)

**Comment by norhh** [comment] 2018-06-19 17:30
if i can confirmation from @b-mueller that this patch fixes that error, i will test and then merge it into the repo.

**Closed** 2018-06-23 05:13 UTC
Labels: Review, bug
